; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
build_src_filter = +<*> -<ESP32/> -<Android/>
build_unflags = 
	-std=gnu++11
    -std=gnu++14
build_flags = 
	-I include
	-std=gnu++17
	-mcpu=cortex-m7
	-mfloat-abi=hard
	-mfpu=fpv5-d16
	-O3
	-ffast-math
	-funroll-loops
	-ftree-vectorize
	-fomit-frame-pointer
	-D USB_MIDI_AUDIO_SERIAL
	-D ARM_MATH_CM7
	-D ARM_MATH_MATRIX_CHECK
	-D ARM_MATH_ROUNDING
	-D ARM_MATH_LOOPUNROLL
	-D ARM_FAST_MATH_TABLES
	-D ARM_FFT_ALLOW_TABLES
	-D USB_MIDI_AUDIO_SERIAL
	-Wall
build_type = release
upload_protocol = teensy-gui
monitor_speed = 115200
monitor_filters = send_on_enter
monitor_echo = yes

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_src_filter = +<*> -<Teensy/> -<Android/>
build_unflags = 
	-std=gnu++11
    -std=gnu++14
build_flags =
	-I include
	-std=gnu++17
	-DARDUINO_USB_MODE=1
  	-DARDUINO_USB_CDC_ON_BOOT=1
    -DCONFIG_ESP_MAIN_TASK_STACK_SIZE=16384
    -DCONFIG_ARDUINO_LOOP_STACK_SIZE=16384
build_type = release
board_build.partitions = default.csv
board_build.arduino.memory_type = qio_qspi
upload_speed = 921600
monitor_speed = 115200
monitor_filters = send_on_enter
monitor_echo = yes
lib_deps =
    tanakamasayuki/TensorFlowLite_ESP32